// ============================================================
// MOCK DATA — Realistic demo data for the REMS dashboard
// ============================================================

export const OWNER = {
  id: 'owner-001',
  fullName: 'Abdulrahman Al-Rashidi',
  email: 'abdualhumud@elm.sa',
  currency: 'SAR',
  propertyCount: 4,
};

export const PROPERTIES = [
  { id: 'p1', name: 'Riyadh Luxury Apartment', city: 'Riyadh', type: 'APARTMENT', units: 3 },
  { id: 'p2', name: 'Jeddah Corniche Villa', city: 'Jeddah', type: 'VILLA', units: 1 },
  { id: 'p3', name: 'Diriyah Heritage Chalet', city: 'Riyadh', type: 'CHALET', units: 2 },
  { id: 'p4', name: 'AlUla Desert Studio', city: 'AlUla', type: 'STUDIO', units: 1 },
];

export const KPI_DATA = {
  totalRevenue: 284_750,
  netPayout: 218_432,
  totalBookings: 87,
  averageOccupancy: 73.4,
  adr: 1_248,
  revPAR: 915,
  revenueTrend: 18.2,
  occupancyTrend: 6.7,
};

export const MONTHLY_REVENUE = [
  { month: 'Aug', revenue: 18200, bookings: 6 },
  { month: 'Sep', revenue: 22400, bookings: 8 },
  { month: 'Oct', revenue: 31800, bookings: 11 },
  { month: 'Nov', revenue: 28600, bookings: 9 },
  { month: 'Dec', revenue: 42000, bookings: 14 },
  { month: 'Jan', revenue: 38900, bookings: 12 },
  { month: 'Feb', revenue: 51200, bookings: 15 },
  { month: 'Mar', revenue: 51650, bookings: 12 },
];

export const CHANNEL_BREAKDOWN = [
  { channel: 'Booking.com', bookings: 34, revenue: 108_320, commission: 16_248, share: 39, color: '#003580' },
  { channel: 'Airbnb',      bookings: 28, revenue: 91_400,  commission: 2_742,  share: 32, color: '#FF5A5F' },
  { channel: 'Gathern',     bookings: 18, revenue: 58_230,  commission: 5_823,  share: 21, color: '#00a651' },
  { channel: 'Direct',      bookings: 7,  revenue: 26_800,  commission: 0,      share: 8,  color: '#f59e0b' },
];

export const RECENT_BOOKINGS = [
  {
    id: 'BK-1091',
    channel: 'Booking.com',
    channelColor: '#003580',
    property: 'Riyadh Luxury Apartment',
    unit: 'Unit A',
    guest: 'Mohammed Al-Otaibi',
    checkIn: '2026-02-22',
    checkOut: '2026-02-26',
    nights: 4,
    amount: 5_248,
    status: 'CONFIRMED',
    statusColor: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'BK-1090',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    property: 'Jeddah Corniche Villa',
    unit: 'Main Villa',
    guest: 'Sarah Thompson',
    checkIn: '2026-02-24',
    checkOut: '2026-03-01',
    nights: 5,
    amount: 8_750,
    status: 'CONFIRMED',
    statusColor: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'BK-1089',
    channel: 'Gathern',
    channelColor: '#00a651',
    property: 'Diriyah Heritage Chalet',
    unit: 'Chalet 1',
    guest: 'Khalid Al-Dosari',
    checkIn: '2026-02-20',
    checkOut: '2026-02-23',
    nights: 3,
    amount: 3_600,
    status: 'CHECKED_IN',
    statusColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'BK-1088',
    channel: 'Direct',
    channelColor: '#f59e0b',
    property: 'AlUla Desert Studio',
    unit: 'Studio',
    guest: 'Emma Wilson',
    checkIn: '2026-02-18',
    checkOut: '2026-02-21',
    nights: 3,
    amount: 4_200,
    status: 'CHECKED_OUT',
    statusColor: 'bg-gray-100 text-gray-600',
  },
  {
    id: 'BK-1087',
    channel: 'Booking.com',
    channelColor: '#003580',
    property: 'Riyadh Luxury Apartment',
    unit: 'Unit B',
    guest: 'Fatima Al-Zahrani',
    checkIn: '2026-02-15',
    checkOut: '2026-02-18',
    nights: 3,
    amount: 3_744,
    status: 'CHECKED_OUT',
    statusColor: 'bg-gray-100 text-gray-600',
  },
  {
    id: 'BK-1086',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    property: 'Diriyah Heritage Chalet',
    unit: 'Chalet 2',
    guest: 'Ravi Sharma',
    checkIn: '2026-03-05',
    checkOut: '2026-03-10',
    nights: 5,
    amount: 6_000,
    status: 'PENDING',
    statusColor: 'bg-amber-100 text-amber-700',
  },
];

export const CALENDAR_EVENTS = [
  { id: 'e1', unit: 'Riyadh — Unit A', start: 22, end: 26, channel: 'Booking.com', color: 'bg-blue-900 text-white', guest: 'Mohammed Al-Otaibi' },
  { id: 'e2', unit: 'Jeddah Villa',    start: 24, end: 29, channel: 'Airbnb',      color: 'bg-rose-500 text-white', guest: 'Sarah Thompson' },
  { id: 'e3', unit: 'Diriyah — C1',   start: 20, end: 23, channel: 'Gathern',     color: 'bg-emerald-600 text-white', guest: 'Khalid Al-Dosari' },
  { id: 'e4', unit: 'AlUla Studio',   start: 18, end: 21, channel: 'Direct',      color: 'bg-amber-500 text-white', guest: 'Emma Wilson' },
  { id: 'e5', unit: 'Riyadh — Unit B',start: 15, end: 18, channel: 'Booking.com', color: 'bg-blue-900 text-white', guest: 'Fatima Al-Zahrani' },
  { id: 'e6', unit: 'Diriyah — C2',   start: 28, end: 32, channel: 'Airbnb',      color: 'bg-rose-500 text-white', guest: 'Ravi Sharma' },
];

export const CHANNEL_SYNC_STATUS = [
  {
    channel: 'Booking.com',
    logo: '🔵',
    isConnected: true,
    syncMethod: 'Webhook',
    lastSync: '2 min ago',
    bookingsToday: 2,
    pending: 0,
    failed: 0,
    color: 'text-blue-700',
    bg: 'bg-blue-50',
  },
  {
    channel: 'Airbnb',
    logo: '🔴',
    isConnected: true,
    syncMethod: 'Webhook',
    lastSync: '5 min ago',
    bookingsToday: 1,
    pending: 1,
    failed: 0,
    color: 'text-rose-600',
    bg: 'bg-rose-50',
  },
  {
    channel: 'Gathern',
    logo: '🟢',
    isConnected: true,
    syncMethod: 'Polling/120s',
    lastSync: '47 sec ago',
    bookingsToday: 0,
    pending: 0,
    failed: 0,
    color: 'text-emerald-700',
    bg: 'bg-emerald-50',
  },
];

export const INBOX_MESSAGES = [
  {
    id: 'm1',
    bookingId: 'BK-1091',
    channel: 'Booking.com',
    channelColor: '#003580',
    guest: 'Mohammed Al-Otaibi',
    property: 'Riyadh Luxury Apartment',
    message: 'Hi, could you arrange early check-in at 11am? We have a flight arriving in the morning.',
    isRead: false,
    time: '10:42 AM',
  },
  {
    id: 'm2',
    bookingId: 'BK-1090',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    guest: 'Sarah Thompson',
    property: 'Jeddah Corniche Villa',
    message: 'The apartment is absolutely stunning! Could you recommend a good restaurant nearby?',
    isRead: false,
    time: '9:15 AM',
  },
  {
    id: 'm3',
    bookingId: 'BK-1089',
    channel: 'Gathern',
    channelColor: '#00a651',
    guest: 'Khalid Al-Dosari',
    property: 'Diriyah Heritage Chalet',
    message: 'شكراً جزيلاً على الاستقبال الرائع. هل يمكن تمديد الإقامة ليلة إضافية؟',
    isRead: true,
    time: 'Yesterday',
  },
  {
    id: 'm4',
    bookingId: 'BK-1086',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    guest: 'Ravi Sharma',
    property: 'Diriyah Heritage Chalet',
    message: 'Looking forward to the stay! What is the best way to get from Riyadh airport to the property?',
    isRead: true,
    time: 'Yesterday',
  },
];

// ── Extended unit data with pricing, amenities, insurance ──────────────
export const UNITS = [
  {
    id: 'u1', propertyId: 'p1', propertyName: 'Riyadh Luxury Apartment',
    name: 'Unit A — 3BR Deluxe', type: 'APARTMENT', size: 180, floor: 5,
    beds: 3, baths: 2,
    amenities: ['wifi','ac','kitchen','tv','washer','parking','balcony'],
    city: 'Riyadh', district: 'Al-Malaz', street: 'King Fahd Rd', postal: '12345',
    lat: 24.6877, lng: 46.7219,
    basePrice: 1248, weekendSurge: 20, seasonalPeak: 1.4, cleaningFee: 150, securityDeposit: 2000, minStay: 2,
    channels: ['Booking.com','Airbnb','Gathern'],
    status: 'ACTIVE', occupancy: 82, revenue: 38400, photos: 6,
    insuranceProvider: 'Daman',
    color: '#3B82F6',
  },
  {
    id: 'u2', propertyId: 'p1', propertyName: 'Riyadh Luxury Apartment',
    name: 'Unit B — 2BR Classic', type: 'APARTMENT', size: 130, floor: 3,
    beds: 2, baths: 2,
    amenities: ['wifi','ac','kitchen','tv','balcony'],
    city: 'Riyadh', district: 'Al-Malaz', street: 'King Fahd Rd', postal: '12345',
    lat: 24.6877, lng: 46.7219,
    basePrice: 950, weekendSurge: 15, seasonalPeak: 1.3, cleaningFee: 120, securityDeposit: 1500, minStay: 2,
    channels: ['Booking.com','Gathern'],
    status: 'ACTIVE', occupancy: 74, revenue: 27800, photos: 4,
    insuranceProvider: 'Daman',
    color: '#3B82F6',
  },
  {
    id: 'u3', propertyId: 'p2', propertyName: 'Jeddah Corniche Villa',
    name: 'Main Villa — 5BR Sea View', type: 'VILLA', size: 450, floor: 0,
    beds: 5, baths: 4,
    amenities: ['wifi','ac','kitchen','tv','washer','parking','pool','balcony'],
    city: 'Jeddah', district: 'Al-Corniche', street: 'Corniche Rd', postal: '23542',
    lat: 21.5169, lng: 39.1797,
    basePrice: 1750, weekendSurge: 30, seasonalPeak: 1.6, cleaningFee: 350, securityDeposit: 5000, minStay: 3,
    channels: ['Airbnb','Gathern'],
    status: 'ACTIVE', occupancy: 67, revenue: 42600, photos: 12,
    insuranceProvider: 'Wafi',
    color: '#8B5CF6',
  },
  {
    id: 'u4', propertyId: 'p3', propertyName: 'Diriyah Heritage Chalet',
    name: 'Chalet 1 — 4BR Heritage', type: 'CHALET', size: 280, floor: 0,
    beds: 4, baths: 3,
    amenities: ['wifi','ac','kitchen','tv','parking','balcony'],
    city: 'Riyadh', district: 'Diriyah', street: 'At-Turaif Rd', postal: '13712',
    lat: 24.7347, lng: 46.5718,
    basePrice: 1100, weekendSurge: 25, seasonalPeak: 1.5, cleaningFee: 200, securityDeposit: 3000, minStay: 2,
    channels: ['Booking.com','Gathern'],
    status: 'ACTIVE', occupancy: 71, revenue: 29500, photos: 8,
    insuranceProvider: 'Daman',
    color: '#F59E0B',
  },
  {
    id: 'u5', propertyId: 'p3', propertyName: 'Diriyah Heritage Chalet',
    name: 'Chalet 2 — 3BR Garden', type: 'CHALET', size: 220, floor: 0,
    beds: 3, baths: 2,
    amenities: ['wifi','ac','kitchen','parking'],
    city: 'Riyadh', district: 'Diriyah', street: 'At-Turaif Rd', postal: '13712',
    lat: 24.7347, lng: 46.5718,
    basePrice: 900, weekendSurge: 20, seasonalPeak: 1.3, cleaningFee: 180, securityDeposit: 2500, minStay: 2,
    channels: ['Airbnb'],
    status: 'MAINTENANCE', occupancy: 0, revenue: 0, photos: 5,
    insuranceProvider: 'Daman',
    color: '#F59E0B',
  },
  {
    id: 'u6', propertyId: 'p4', propertyName: 'AlUla Desert Studio',
    name: 'Desert Studio — 1BR Eco', type: 'STUDIO', size: 60, floor: 1,
    beds: 1, baths: 1,
    amenities: ['wifi','ac','tv'],
    city: 'AlUla', district: 'Al-Hijr', street: 'Heritage Blvd', postal: '49326',
    lat: 26.6195, lng: 37.9183,
    basePrice: 900, weekendSurge: 40, seasonalPeak: 2.0, cleaningFee: 100, securityDeposit: 1000, minStay: 1,
    channels: ['Booking.com','Airbnb','Gathern'],
    status: 'ACTIVE', occupancy: 71, revenue: 22500, photos: 7,
    insuranceProvider: 'Wafi',
    color: '#10B981',
  },
];

// ── Insurance / Security deposit status per booking ────────────────────
export const INSURANCE_RECORDS = [
  { bookingId: 'BK-1089', guest: 'Khalid Al-Dosari', unit: 'Chalet 1', provider: 'Daman', depositAmount: 3000, status: 'PENDING_INSPECTION', checkoutDate: '2026-02-23' },
  { bookingId: 'BK-1088', guest: 'Emma Wilson',      unit: 'Studio',   provider: 'Wafi',  depositAmount: 1000, status: 'RELEASED',          checkoutDate: '2026-02-21' },
  { bookingId: 'BK-1087', guest: 'Fatima Al-Zahrani',unit: 'Unit B',   provider: 'Daman', depositAmount: 1500, status: 'RELEASED',          checkoutDate: '2026-02-18' },
  { bookingId: 'BK-1091', guest: 'Mohammed Al-Otaibi',unit:'Unit A',   provider: 'Daman', depositAmount: 2000, status: 'HELD',              checkoutDate: '2026-02-26' },
];

// ── Cleaning Providers ─────────────────────────────────────────────────
export const CLEANING_PROVIDERS = [
  { id: 'cp1', type: 'INTERNAL' as const, name: 'Saleh Al-Qahtani',   role: 'Senior Cleaner',  available: true,  rating: 4.9, completedToday: 2 },
  { id: 'cp2', type: 'INTERNAL' as const, name: 'Nora Al-Shammari',   role: 'Housekeeper',     available: true,  rating: 4.7, completedToday: 1 },
  { id: 'cp3', type: 'INTERNAL' as const, name: 'Ahmed Al-Yami',      role: 'Maintenance Tech', available: false, rating: 4.8, completedToday: 3 },
  { id: 'cp4', type: 'EXTERNAL' as const, name: 'Clean Pro KSA',      role: 'Cleaning Company', available: true,  rating: 4.6, completedToday: 0 },
  { id: 'cp5', type: 'EXTERNAL' as const, name: 'Sparkle Services',   role: 'Cleaning Company', available: true,  rating: 4.5, completedToday: 0 },
];

// ── Cleaning Requests (auto-generated from checkouts) ──────────────────
export type CleaningStatus = 'PENDING'|'ASSIGNED'|'IN_PROGRESS'|'COMPLETED'|'INSPECTION_DONE';
export const CLEANING_REQUESTS = [
  {
    id: 'cr1', bookingId: 'BK-1089', unitId: 'u4',
    unitName: 'Chalet 1 — 4BR Heritage', property: 'Diriyah Heritage Chalet',
    checkoutDate: '2026-02-23', checkoutTime: '12:00',
    status: 'PENDING' as CleaningStatus,
    providerType: 'INTERNAL' as const, providerId: null as string | null,
    depositBookingId: 'BK-1089', depositAmount: 3000,
    priority: 'HIGH',
    messages: [
      { from: 'SYSTEM', text: '🔔 Checkout detected — Khalid Al-Dosari — BK-1089. Cleaning request created.', time: '12:01' },
    ],
  },
  {
    id: 'cr2', bookingId: 'BK-1088', unitId: 'u6',
    unitName: 'Desert Studio — 1BR Eco', property: 'AlUla Desert Studio',
    checkoutDate: '2026-02-21', checkoutTime: '11:00',
    status: 'INSPECTION_DONE' as CleaningStatus,
    providerType: 'INTERNAL' as const, providerId: 'cp1',
    depositBookingId: 'BK-1088', depositAmount: 1000,
    priority: 'NORMAL',
    messages: [
      { from: 'SYSTEM',   text: '🔔 Checkout detected — Emma Wilson — BK-1088. Cleaning request created.',  time: '11:01' },
      { from: 'MANAGER',  text: 'Saleh, please clean Studio by 2pm. Guest leaving 5-star review — keep it spotless.', time: '11:05' },
      { from: 'Saleh',    text: 'On my way now. Will be done by 1:30pm inshaAllah.', time: '11:20' },
      { from: 'Saleh',    text: '✅ Cleaning complete. Linen changed, bathroom sanitized, mini bar restocked.', time: '13:25' },
      { from: 'SYSTEM',   text: '✅ Inspection checklist passed. Deposit SAR 1,000 released to guest.', time: '13:45' },
    ],
  },
  {
    id: 'cr3', bookingId: 'BK-1087', unitId: 'u2',
    unitName: 'Unit B — 2BR Classic', property: 'Riyadh Luxury Apartment',
    checkoutDate: '2026-02-18', checkoutTime: '10:00',
    status: 'COMPLETED' as CleaningStatus,
    providerType: 'EXTERNAL' as const, providerId: 'cp4',
    depositBookingId: 'BK-1087', depositAmount: 1500,
    priority: 'NORMAL',
    messages: [
      { from: 'SYSTEM',   text: '🔔 Checkout detected — Fatima Al-Zahrani — BK-1087. Cleaning request created.', time: '10:01' },
      { from: 'MANAGER',  text: 'Clean Pro KSA — please send team to Unit B, 3rd floor. Priority: same-day next guest at 6pm.', time: '10:15' },
      { from: 'Clean Pro',text: 'Team dispatched. ETA 45 mins.', time: '10:20' },
      { from: 'Clean Pro',text: '✅ Cleaned and ready. Photos uploaded to portal.', time: '12:10' },
    ],
  },
];

export const DAILY_OCCUPANCY = [
  { day: 'Feb 15', rate: 75 }, { day: 'Feb 16', rate: 75 },
  { day: 'Feb 17', rate: 75 }, { day: 'Feb 18', rate: 50 },
  { day: 'Feb 19', rate: 50 }, { day: 'Feb 20', rate: 75 },
  { day: 'Feb 21', rate: 100 }, { day: 'Feb 22', rate: 100 },
  { day: 'Feb 23', rate: 75 }, { day: 'Feb 24', rate: 100 },
  { day: 'Feb 25', rate: 100 }, { day: 'Feb 26', rate: 75 },
  { day: 'Feb 27', rate: 50 }, { day: 'Feb 28', rate: 75 },
];
