// ============================================================
// MOCK DATA — Realistic demo data for the REMS dashboard
// ============================================================

export const OWNER = {
  id: 'owner-001',
  fullName: 'Abdulrahman Al-Rashidi',
  email: 'abdualhumud@elm.sa',
  currency: 'SAR',
  propertyCount: 4,
};

export const PROPERTIES = [
  { id: 'p1', name: 'Riyadh Luxury Apartment', city: 'Riyadh', type: 'APARTMENT', units: 3 },
  { id: 'p2', name: 'Jeddah Corniche Villa', city: 'Jeddah', type: 'VILLA', units: 1 },
  { id: 'p3', name: 'Diriyah Heritage Chalet', city: 'Riyadh', type: 'CHALET', units: 2 },
  { id: 'p4', name: 'AlUla Desert Studio', city: 'AlUla', type: 'STUDIO', units: 1 },
];

export const KPI_DATA = {
  totalRevenue: 284_750,
  netPayout: 218_432,
  totalBookings: 87,
  averageOccupancy: 73.4,
  adr: 1_248,
  revPAR: 915,
  revenueTrend: 18.2,
  occupancyTrend: 6.7,
};

export const MONTHLY_REVENUE = [
  { month: 'Aug', revenue: 18200, bookings: 6 },
  { month: 'Sep', revenue: 22400, bookings: 8 },
  { month: 'Oct', revenue: 31800, bookings: 11 },
  { month: 'Nov', revenue: 28600, bookings: 9 },
  { month: 'Dec', revenue: 42000, bookings: 14 },
  { month: 'Jan', revenue: 38900, bookings: 12 },
  { month: 'Feb', revenue: 51200, bookings: 15 },
  { month: 'Mar', revenue: 51650, bookings: 12 },
];

export const CHANNEL_BREAKDOWN = [
  { channel: 'Booking.com', bookings: 34, revenue: 108_320, commission: 16_248, share: 39, color: '#003580' },
  { channel: 'Airbnb',      bookings: 28, revenue: 91_400,  commission: 2_742,  share: 32, color: '#FF5A5F' },
  { channel: 'Gathern',     bookings: 18, revenue: 58_230,  commission: 5_823,  share: 21, color: '#00a651' },
  { channel: 'Direct',      bookings: 7,  revenue: 26_800,  commission: 0,      share: 8,  color: '#f59e0b' },
];

export const RECENT_BOOKINGS = [
  {
    id: 'BK-1091',
    channel: 'Booking.com',
    channelColor: '#003580',
    property: 'Riyadh Luxury Apartment',
    unit: 'Unit A',
    guest: 'Mohammed Al-Otaibi',
    checkIn: '2026-02-22',
    checkOut: '2026-02-26',
    nights: 4,
    amount: 5_248,
    status: 'CONFIRMED',
    statusColor: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'BK-1090',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    property: 'Jeddah Corniche Villa',
    unit: 'Main Villa',
    guest: 'Sarah Thompson',
    checkIn: '2026-02-24',
    checkOut: '2026-03-01',
    nights: 5,
    amount: 8_750,
    status: 'CONFIRMED',
    statusColor: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'BK-1089',
    channel: 'Gathern',
    channelColor: '#00a651',
    property: 'Diriyah Heritage Chalet',
    unit: 'Chalet 1',
    guest: 'Khalid Al-Dosari',
    checkIn: '2026-02-20',
    checkOut: '2026-02-23',
    nights: 3,
    amount: 3_600,
    status: 'CHECKED_IN',
    statusColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'BK-1088',
    channel: 'Direct',
    channelColor: '#f59e0b',
    property: 'AlUla Desert Studio',
    unit: 'Studio',
    guest: 'Emma Wilson',
    checkIn: '2026-02-18',
    checkOut: '2026-02-21',
    nights: 3,
    amount: 4_200,
    status: 'CHECKED_OUT',
    statusColor: 'bg-gray-100 text-gray-600',
  },
  {
    id: 'BK-1087',
    channel: 'Booking.com',
    channelColor: '#003580',
    property: 'Riyadh Luxury Apartment',
    unit: 'Unit B',
    guest: 'Fatima Al-Zahrani',
    checkIn: '2026-02-15',
    checkOut: '2026-02-18',
    nights: 3,
    amount: 3_744,
    status: 'CHECKED_OUT',
    statusColor: 'bg-gray-100 text-gray-600',
  },
  {
    id: 'BK-1086',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    property: 'Diriyah Heritage Chalet',
    unit: 'Chalet 2',
    guest: 'Ravi Sharma',
    checkIn: '2026-03-05',
    checkOut: '2026-03-10',
    nights: 5,
    amount: 6_000,
    status: 'PENDING',
    statusColor: 'bg-amber-100 text-amber-700',
  },
];

export const CALENDAR_EVENTS = [
  { id: 'e1', unit: 'Riyadh — Unit A', start: 22, end: 26, channel: 'Booking.com', color: 'bg-blue-900 text-white', guest: 'Mohammed Al-Otaibi' },
  { id: 'e2', unit: 'Jeddah Villa',    start: 24, end: 29, channel: 'Airbnb',      color: 'bg-rose-500 text-white', guest: 'Sarah Thompson' },
  { id: 'e3', unit: 'Diriyah — C1',   start: 20, end: 23, channel: 'Gathern',     color: 'bg-emerald-600 text-white', guest: 'Khalid Al-Dosari' },
  { id: 'e4', unit: 'AlUla Studio',   start: 18, end: 21, channel: 'Direct',      color: 'bg-amber-500 text-white', guest: 'Emma Wilson' },
  { id: 'e5', unit: 'Riyadh — Unit B',start: 15, end: 18, channel: 'Booking.com', color: 'bg-blue-900 text-white', guest: 'Fatima Al-Zahrani' },
  { id: 'e6', unit: 'Diriyah — C2',   start: 28, end: 32, channel: 'Airbnb',      color: 'bg-rose-500 text-white', guest: 'Ravi Sharma' },
];

export const CHANNEL_SYNC_STATUS = [
  {
    channel: 'Booking.com',
    logo: '🔵',
    isConnected: true,
    syncMethod: 'Webhook',
    lastSync: '2 min ago',
    bookingsToday: 2,
    pending: 0,
    failed: 0,
    color: 'text-blue-700',
    bg: 'bg-blue-50',
  },
  {
    channel: 'Airbnb',
    logo: '🔴',
    isConnected: true,
    syncMethod: 'Webhook',
    lastSync: '5 min ago',
    bookingsToday: 1,
    pending: 1,
    failed: 0,
    color: 'text-rose-600',
    bg: 'bg-rose-50',
  },
  {
    channel: 'Gathern',
    logo: '🟢',
    isConnected: true,
    syncMethod: 'Polling/120s',
    lastSync: '47 sec ago',
    bookingsToday: 0,
    pending: 0,
    failed: 0,
    color: 'text-emerald-700',
    bg: 'bg-emerald-50',
  },
];

export const INBOX_MESSAGES = [
  {
    id: 'm1',
    bookingId: 'BK-1091',
    channel: 'Booking.com',
    channelColor: '#003580',
    guest: 'Mohammed Al-Otaibi',
    property: 'Riyadh Luxury Apartment',
    message: 'Hi, could you arrange early check-in at 11am? We have a flight arriving in the morning.',
    isRead: false,
    time: '10:42 AM',
  },
  {
    id: 'm2',
    bookingId: 'BK-1090',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    guest: 'Sarah Thompson',
    property: 'Jeddah Corniche Villa',
    message: 'The apartment is absolutely stunning! Could you recommend a good restaurant nearby?',
    isRead: false,
    time: '9:15 AM',
  },
  {
    id: 'm3',
    bookingId: 'BK-1089',
    channel: 'Gathern',
    channelColor: '#00a651',
    guest: 'Khalid Al-Dosari',
    property: 'Diriyah Heritage Chalet',
    message: 'شكراً جزيلاً على الاستقبال الرائع. هل يمكن تمديد الإقامة ليلة إضافية؟',
    isRead: true,
    time: 'Yesterday',
  },
  {
    id: 'm4',
    bookingId: 'BK-1086',
    channel: 'Airbnb',
    channelColor: '#FF5A5F',
    guest: 'Ravi Sharma',
    property: 'Diriyah Heritage Chalet',
    message: 'Looking forward to the stay! What is the best way to get from Riyadh airport to the property?',
    isRead: true,
    time: 'Yesterday',
  },
];

export const DAILY_OCCUPANCY = [
  { day: 'Feb 15', rate: 75 }, { day: 'Feb 16', rate: 75 },
  { day: 'Feb 17', rate: 75 }, { day: 'Feb 18', rate: 50 },
  { day: 'Feb 19', rate: 50 }, { day: 'Feb 20', rate: 75 },
  { day: 'Feb 21', rate: 100 }, { day: 'Feb 22', rate: 100 },
  { day: 'Feb 23', rate: 75 }, { day: 'Feb 24', rate: 100 },
  { day: 'Feb 25', rate: 100 }, { day: 'Feb 26', rate: 75 },
  { day: 'Feb 27', rate: 50 }, { day: 'Feb 28', rate: 75 },
];
